name: Bug report
description: Report a reproducible bug
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to ...
        2. Tap ...
        3. See error ...
    validations:
      required: true
  - type: input
    id: flutter
    attributes:
      label: Flutter version
      placeholder: flutter --version
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Linux
        - Android
        - iOS
        - Web
